'use strict';

const fs = require('node:fs');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '../..');
const destination = path.join(repoRoot, 'engine/dist/n8n-code-node.js');

// Small, deterministic CommonJS bundler for this engine's relative JS/JSON
// imports. Build-time filesystem access only; the resulting node is standalone.
function buildBundle() {
  const sources = new Map();
  const dependencies = {};
  function visit(filename) {
    const id = path.relative(repoRoot, filename).split(path.sep).join('/');
    if (id.startsWith('../')) throw new Error('Bundle imports must stay within StudyGPS');
    if (sources.has(id)) return id;
    const source = fs.readFileSync(filename, 'utf8');
    sources.set(id, path.extname(filename) === '.json' ? `module.exports = ${JSON.stringify(JSON.parse(source))};` : source.trimEnd());
    dependencies[id] = {};
    if (path.extname(filename) !== '.json') {
      for (const match of source.matchAll(/\brequire\((['"])([^'"]+)\1\)/g)) {
        const specifier = match[2];
        if (!specifier.startsWith('.')) throw new Error(`Runtime external dependency is forbidden: ${specifier}`);
        const base = path.resolve(path.dirname(filename), specifier);
        const resolved = [base, `${base}.js`, `${base}.json`].find((candidate) => fs.existsSync(candidate) && fs.statSync(candidate).isFile());
        if (!resolved) throw new Error(`Cannot bundle ${id}: ${specifier}`);
        dependencies[id][specifier] = visit(resolved);
      }
    }
    return id;
  }
  const entry = visit(path.join(repoRoot, 'engine/n8n-adapter.js'));
  const ids = [...sources.keys()].sort();
  const functions = ids.map((id) => `${JSON.stringify(id)}: function(module, exports, require) {\n${sources.get(id)}\n}`).join(',\n');
  const mappings = Object.fromEntries(ids.map((id) => [id, dependencies[id]]));
  return `// GENERATED by node engine/scripts/build-n8n.js; edit source, then rebuild.\n// n8n Code node: JavaScript / Run Once for All Items / exactly one input item.\n// Local parity tested; 尚未在真实 n8n 环境验证.\n'use strict';\nconst __modules = {\n${functions}\n};\nconst __dependencies = ${JSON.stringify(mappings, null, 2)};\nconst __cache = Object.create(null);\nfunction __load(id) {\n  if (__cache[id]) return __cache[id].exports;\n  if (!Object.hasOwn(__modules, id)) throw new Error('Unknown bundled module: ' + id);\n  const module = { exports: {} };\n  __cache[id] = module;\n  const require = (specifier) => {\n    if (!Object.hasOwn(__dependencies[id], specifier)) throw new Error('External imports are disabled: ' + specifier);\n    return __load(__dependencies[id][specifier]);\n  };\n  __modules[id](module, module.exports, require);\n  return module.exports;\n}\nreturn __load(${JSON.stringify(entry)}).runCodeNode($input.all());\n`;
}

if (require.main === module) {
  const content = buildBundle();
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(destination) || fs.readFileSync(destination, 'utf8') !== content) {
      console.error('The n8n artifact is stale or missing. Run node engine/scripts/build-n8n.js');
      process.exitCode = 1;
    } else console.log('n8n artifact matches the current core source.');
  } else {
    fs.mkdirSync(path.dirname(destination), { recursive: true });
    fs.writeFileSync(destination, content);
    console.log('Generated engine/dist/n8n-code-node.js');
  }
}

module.exports = { buildBundle };
